name: Preview Update

on:
  push:
    branches:
      - main

jobs:
  publish_update:
    name: Publish Preview Update
    type: update
    params:
      channel: preview
      message: ${{ github.event.head_commit.message }}

  notify_slack:
    name: Notify Slack
    needs: [publish_update]
    type: slack
    params:
      webhook_url: ${{ env.SLACK_WEBHOOK_URL }}
      payload:
        blocks:
          - type: header
            text:
              type: plain_text
              text: "New Preview Update Ready"
          - type: section
            text:
              type: mrkdwn
              text: "${{ github.event.head_commit.message }}"
          - type: section
            fields:
              - type: mrkdwn
                text: "*Branch:*\n${{ github.ref_name }}"
              - type: mrkdwn
                text: "*Update:*\nexp://u.expo.dev/cd70b552-8a0a-4d7e-9587-e43e30776839/group/${{ needs.publish_update.outputs.first_update_group_id }}"
